### ISSUE TITLE
enhancement: 구독 설정 후 출력되는 Embed 색상 변경

### ISSUE THREAD

**Issue by jub3907** [charon-aesther/aesther-discord-bot#2]
##  목적
* Embed 디자인 변경

## 작업 상세 내용
각 멤버별 구독 설정 후, 출력되는 Embed 좌측의 색상 변경.
![image](https://github.com/charon-aesther/aesther-discord-bot/assets/58246682/7f66f1b3-94b2-4a04-bb5c-3aa2b1d946c7)

## 참고 사항
각 멤버 별 색상 코드는 다음과 같음.
미카 : #fade78
에리스 : #4edeeb
엘리 : #fe9ec1
카린 : #e75262
아리사 : #a671d4

에스더 공통은 흰색이 어떨까 합니다. #ffffff 

* [Discord.js Document about Embed](https://discordjs.guide/popular-topics/embeds.html#embed-preview)

이슈에 라벨 설정 권한이 따로 없어, 제목에 붙였습니다.

**Comment by charon-aesther** [comment]
이슈 올려주셔서 감사합니다! https://github.com/charon-aesther/aesther-discord-bot/pull/3 수정사항 확인해주세요
